### PR TITLE
Workaround bug in the GG by forcing the pins to be updated in order

### PR DESCRIPTION
**Pull request by shardros**
One OO solution for #29 

Does make some interfaces tigheter coupled but there is no nice way to do this which I can think of.s

My GG does not seem to be responding to commands to GPIO on `master` so not sure what is going on there. Not tested this branch as a result.

### CODE REVIEW

**Comment by WillMunns** [comment]
I've made a couple of changes to work with this new scheme. reset.py appears to instantiate bits of the greengiant on demand from Shepherd. It assumed that the GPIO were stateless, so I have changed it to make the full list, and update through that. Let me know if I have understood this incorrectly - it appears to work on a brain.

Originally the state of the pin internally was configured as None - presumably to stop people poking GPIO that they had not touched. This breaks now that every touch updates everything. The change to default this to INPUT rather than None matches reality, but I'm not certain its best to do it here, or to check for None in the setter and set it to INPUT there and would keep some of the "you haven't explicitly configured this yet" behavior.

**Comment by shardros** [comment]
Added update in init to ensure that the state of the GG does actually match the new assumed state of `INPUT`. Tested PR with:

```py
import robot
import time

R = robot.Robot()

R.gpio[1].mode = robot.OUTPUT
R.gpio[2].mode = robot.OUTPUT
R.gpio[3].mode = robot.OUTPUT
R.gpio[4].mode = robot.OUTPUT

R.gpio[1].digital = False
R.gpio[2].digital = False
R.gpio[3].digital = False
R.gpio[4].digital = False

print("Configured outputs")

time.sleep(10)

R.gpio[1].digital = True
R.gpio[2].digital = True
R.gpio[3].digital = True
R.gpio[4].digital = True

print("Configured outputs")

time.sleep(10)

R.gpio[2].mode = robot.INPUT
```

Happy to merge.

**Comment by shardros** [comment]
@WillMunns Not sure if you have seen but I am happy for this to be merged to master now.

**Comment by shardros** [comment]
@WillMunns Should this be merged? Was it already patched in. Does `master` reflect the current state of the brains?

**Comment by shardros** [comment]
Given that we are now in the summer merge window, I think that this was merged in the end I am just going to merge this so that any other branches have it

**Pull request merged**
